name: update-lambda

on:
    push:
        branches:
            - main
        # maual trigger
    workflow_dispatch:

env:
    AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
    AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    AWS_REGION: 'us-east-1'

    S3_BUCKET: 'nk-lambda-code'
    S3_KEY: 'nkLambdaPy.zip'
    LAMBDA_FUNCTION_NAME: 'nkLambdaPy'

jobs:
    deploy:
        runs-on: ubuntu-latest

        permissions:
            contents: read
            id-token: write
            actions: write

        steps:
            - name: Checkout code
              uses: actions/checkout@v2
              with:
                  fetch-depth: 0  # To fetch the current commit and its parent (so we can compare)

            - name: create .env file
              run: |
                touch .env
                # echo AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }} >> .env
                # echo AWS_SECRET_ACCESS_KEY="${{ secrets.AWS_SECRET_ACCESS_KEY }}" >> .env
                echo AWS_REGION="us-east-1" >> .env
                echo NAME="Nadeem" >> .env
                echo "printing .env file..."
                cat .env
            
            - name: Setup AWS CLI
              uses: aws-actions/configure-aws-credentials@v1
              with:
                  aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
                  aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                  aws-region: ${{ env.AWS_REGION }}
                
              
            - name: Deploy Lambda functions
              run: |

                # Zip src folder called 'src' and upload to S3
                zip -r ${{ env.S3_KEY }} src
                

                aws s3 cp ${{ env.S3_KEY }} s3://${{ env.S3_BUCKET }}

                aws lambda update-function-code \
                    --function-name ${{ env.LAMBDA_FUNCTION_NAME }} \
                    --s3-bucket ${{ env.S3_BUCKET }} \
                    --s3-key ${{ env.S3_KEY }}

                # Cleanup
                